name: backend

dependencies:
  - python=3.10.9
  - pip=23.0.1
  - psycopg2
  - pip:
    - django==4.1.7
    - djangorestframework==3.14.0
    - djangorestframework_simplejwt==5.2.2
    - drf-yasg==1.21.5
    - pillow==9.4.0
    - flake8==6.0.0
    - django-cors-headers

