name: luna
dependencies:
  - python=3.10.4
  - pip== 23.0.1
  - psycopg2==2.9.3
  - pip:
    - django==4.1.1
    - djangorestframework==3.14.0
    - djangorestframework-simplejwt==5.2.2
    - drf-yasg==1.21.5
    - django-cors-headers==3.14.0
    - flake8==6.0.0
    - gunicorn==20.1.0
    - Pillow==9.4.0